### PR TITLE
Update setup-go per go1.14 release

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
`npm audit fix` does not fix the vulnerabilities
```
found 13 moderate severity vulnerabilities in 1194431 scanned packages
  13 vulnerabilities require manual review. See the full report for details.
##[error]Process completed with exit code 1.
```

**Comment by chenrui333** [comment]
Still dont have a good solution for `moderate` package vulnerabilities. 

Move the audit-level to `critical`.

**Comment by chenrui333** [comment]
@bryanmacfarlane ready for review.

**Comment by bryanmacfarlane** [comment]
updating the json file doesn't really add more test coverage / validation.  It was never intended to be kept up to date - only to have enough data to validate the scenarios.  Keeping it up to date also has a downside of growing the actions size (pulled at runtime) with no extra test coverage.  

I am interested in eliminating vulnerability reports so if you want to split that into separate PRs, we can take that.

**Comment by chenrui333** [comment]
Sounds good, I will split the npm change into a separate PR.

**Comment by bryanmacfarlane** [comment]
Fixed in another PR.  Thanks!

**Pull request closed without merging**
