### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Comment by MagpieMaggie** [comment]
#13
#BeKind
M. Combs
Billie Eillish
Billie Ellish
#10

**Comment by oscard0m** [comment]
Hi @brcrista ! COuld I get more info on why this PR has been closed?

Thanks

**Comment by brcrista** [comment]
@oscard0m Sorry, to be honest I mistook this for a spam PR.  (We get a lot of those.)  I see now that the relevant change is

```yml
     - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
```

I can't reopen this PR because it looks like your fork no longer exists, but if you can recreate the PR without the extra formatting changes we can give it a look.

It would also be helpful if you could show us what kind of speedup we observe from caching.

**Comment by oscard0m** [comment]
I had to recreate it in https://github.com/actions/setup-go/pull/179

**Pull request closed without merging**
