### PR TITLE
Extract archive fix

### LINKED ISSUE #241: Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format. - Windows Runner
**Description:**
Setup Windows 10 Runner without go installed already.
After setting up I have a step on my workflow: actions/setup-go@v3
Placed the full error at the bottom.

**Action version:**
actions/setup-go@v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
go 1.18

**Repro steps:**  
Setup a self hosted runner on a fresh Windows 10 install.
Specify a step in a go project to use acitons/setup-go@v3 on the self hosted windows runner.
You should get the error specified below.

**Expected behavior:**
During the extract process go should be extracted.

**Actual behavior:**
Receive the following error.
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.

```
Run actions/setup-go@v3
Setup go version spec 1.18
Attempting to download 1.18...
matching 1.18...
Acquiring 1.18.3 from https://github.com/actions/go-versions/releases/download/1.18.3-2426432064/go-1.18.3-win32-x64.zip
Extracting Go...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner\_work\_temp\69939204-4b8f-4ec8-b18f-b0dc2509d44c' -DestinationPath 'C:\Users\User\actions-runner\_work\_temp\43363100-5525-4011-867d-ef3863a56e8a' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\User\actions-runner\_work\_temp\69939204-4b8f-4ec8-b18f-b0dc2509d44c', 'C:\Users\User\actions-runner\_work\_temp\43363100-5525-4011-867d-ef3863a56e8a', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
Falling back to download directly from Go
Install from dist
Acquiring go1.18.3 from https://storage.googleapis.com/golang/go1.18.3.windows-amd64.zip
Extracting Go...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner\_work\_temp\8352c1a6-99ab-4b64-9920-1[15](https://github.com/redanthrax/rmmagent/runs/7097201014?check_suite_focus=true#step:3:16)dfe35207b' -DestinationPath 'C:\Users\User\actions-runner\_work\_temp\7bd5e377-42b4-4930-8126-a6342480422f' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\User\actions-runner\_work\_temp\8352c1a6-99ab-4b64-9920-115dfe35207b', 'C:\Users\User\actions-runner\_work\_temp\7bd5e377-42b4-4930-8126-a6342480422f', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
Error: Failed to download version 1.[18](https://github.com/redanthrax/rmmagent/runs/7097201014?check_suite_focus=true#step:3:19): Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

### PR DESCRIPTION
**Pull request by redanthrax**
**Description:**
Updated tool cache and fixed extract issue on windows.

**Related issue:**
Fixes #241 

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by marko-zivic-93 — APPROVED** [review]

**Comment by redanthrax** [comment]
Hello @dmitry-shibanov. Yes after the changes the self hosted runner works as expected. Basically Extract-Archive expects a .zip file extension so when using the filename instead of the randomly generated filename in Windows it works as expected.

**Comment by panticmilos** [comment]
Hi @redanthrax, can you resolve conflicts with the main branch?

**Comment by redanthrax** [comment]
@panticmilos I have resolved the conflicts.

**Comment by panticmilos** [comment]
Hi @redanthrax,

Could you run `npm run pre-checkin` again and push? One check for the dist folder is failing

**Comment by panticmilos** [comment]
@redanthrax, still has conflicts with main branch :(

**Comment by panticmilos** [comment]
@redanthrax, just a gentle ping ☎️

**Comment by redanthrax** [comment]
Closed in favor of #250

**Pull request closed without merging**
