### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by ethomson**

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
I don't think this is relevant anymore as the latest v2-beta (master) changes did much of this.  @ethomson can you look at the current state in master and see if you still want changes?

**Review by Last801King — COMMENTED** [review]
gh pr checkout 29

**Comment by MrJ78** [comment]
Bonjour

**Comment by q464pp** [comment]
可以拉取合併嗎 謝謝

**Pull request closed without merging**
